// Menukaart van Zusje (overgenomen van de papieren kaart).
// veg = vegetarisch, z = Zusje klassiekertje. Drankprijzen in euro's.
window.ZUSJE_MENU = {
  arrangementen: {
    bourgondisch: { naam: "Bourgondisch Genieten", prijs: 43.80, perRonde: 2 },
    drie: { naam: "Arrangement 3 gerechtjes", prijs: 15.70, aantal: 3 },
    vier: { naam: "Arrangement 4 gerechtjes", prijs: 20.30, aantal: 4 },
    bijgerechtPrijs: 2.00,
    maxArrangementPersonen: 6,
  },

  gerechten: [
    { cat: "voor", nr: 1, naam: "Charcuterie bordje", omschr: "Met Manchego, serranoham, fuet en vijgenjam" },
    { cat: "voor", nr: 2, naam: "Surimisalade", omschr: "In een bootje van Little Gem sla met frisse appeltjes en Noorse garnalen" },
    { cat: "voor", nr: 3, naam: "Tartaar van rode biet", omschr: "Met gekarameliseerde geitenkaas en vijgenjam", veg: true },
    { cat: "voor", nr: 4, naam: "Seizoensvoorgerechtje", omschr: "Vraag onze collega's naar het gerechtje van dit seizoen" },
    { cat: "voor", nr: 5, naam: "Gerookte zalm", omschr: "Op gegrild flatbread met zoete aardappelspread" },
    { cat: "voor", nr: 6, naam: "Geitenkaasje in spek", omschr: "Met honing-tijmsaus", z: true },
    { cat: "voor", nr: 7, naam: "Bloemkool bites", omschr: "Met Little Gem sla, boekweitsalade en crème van doperwten", veg: true },
    { cat: "voor", nr: 8, naam: "Steak tartaar", omschr: "Met brioche toast, cornichons en truffelmayo" },
    { cat: "voor", nr: 9, naam: "Beef tataki", omschr: "Met krokante uitjes en hoisin mayo" },
    { cat: "voor", nr: 10, naam: "Tonijntartaar", omschr: "Met wakame, sriracha mayo en soja garlic" },
    { cat: "voor", nr: 11, naam: "Tomaten-crèmesoepje", omschr: "Met Parmezaanschuim", veg: true },
    { cat: "voor", nr: 12, naam: "Carpaccio", omschr: "Volgens Zusje's recept met truffelmayo", z: true },
    { cat: "voor", nr: 13, naam: "Falafelballetjes", omschr: "Met een naanbroodje en zoetzure rode kool", veg: true },
    { cat: "voor", nr: 14, naam: "Caesarsalade", omschr: "Met krokante kippenhaas, Parmezaanse kaas en pappadums" },
    { cat: "voor", nr: 15, naam: "Gegrilde courgette", omschr: "Op flatbread met ricotta, Parmezaanse kaas en kruidenolie", veg: true },
    { cat: "voor", nr: 16, naam: "Tuna sandwich", omschr: "Met zoete aardappelspread" },
    { cat: "voor", nr: 17, naam: "Oma's draadjesvlees", omschr: "Op eigen wijze met bloemkoolsalade en piccalilly", z: true },

    { cat: "hoofd", nr: 18, naam: "Chicken en Waffles", omschr: "Met bacon en maple syrup", z: true },
    { cat: "hoofd", nr: 19, naam: "Knoflookgamba's", omschr: "Met gekruide orzo en frisse citroen" },
    { cat: "hoofd", nr: 20, naam: "Groene curry", omschr: "Met rijst, limoen en rode peper", veg: true },
    { cat: "hoofd", nr: 21, naam: "Frietje stoofvlees", omschr: "Ouderwets lekker!" },
    { cat: "hoofd", nr: 22, naam: "Gegrild varkenshaasje", omschr: "Met geroosterde bospeen, baconjam, aardappelgratin en saliejus" },
    { cat: "hoofd", nr: 23, naam: "Kaaskroketje", omschr: "Met brioche toast, Hollandaisesaus en augurkenrelish", veg: true },
    { cat: "hoofd", nr: 24, naam: "Pepersteak", omschr: "Lekker met frietjes en pepersaus" },
    { cat: "hoofd", nr: 25, naam: "Groentequiche", omschr: "Met gegrilde groente, feta en gepofte tomaat", veg: true },
    { cat: "hoofd", nr: 26, naam: "Kipsateetje", omschr: "Met mihoen, atjar, pindasaus en kentang" },
    { cat: "hoofd", nr: 27, naam: "Grillburger", omschr: "Vega met bruschetta salsa, cheddar en remouladesaus", veg: true },
    { cat: "hoofd", nr: 28, naam: "Klassiek schnitzeltje", omschr: "Met rösti en Preiselbeeren" },
    { cat: "hoofd", nr: 29, naam: "Groentelasagne", omschr: "Met Parmezaanschuim en gepofte tomaat", veg: true, z: true },
    { cat: "hoofd", nr: 30, naam: "Bao bun", omschr: "Met krokante gamba en sriracha mayo" },
    { cat: "hoofd", nr: 31, naam: "Shortrib", omschr: "Op een rösti met rendang van witte kool" },
    { cat: "hoofd", nr: 32, naam: "Ossenhaasspiesje", omschr: "Met mihoen en Thai-dressing" },
    { cat: "hoofd", nr: 33, naam: "Fish and chips", omschr: "Met remouladesaus" },
    { cat: "hoofd", nr: 34, naam: "Rendang van shiitake", omschr: "Met rijst, atjar, kentang en cassave kroepoek", veg: true },
    { cat: "hoofd", nr: 35, naam: "Wrap pollo", omschr: "Met een krokante verrassing van jalapeño en kaas" },
    { cat: "hoofd", nr: 36, naam: "Hotdog deluxe", omschr: "Met een jalapeño-kaasworstje, zuurkool en mosterd" },
    { cat: "hoofd", nr: 37, naam: "Wellington", omschr: "Van champignons met aardappelpuree en Parmezaanschuim", veg: true },
    { cat: "hoofd", nr: 38, naam: "Rib bites", omschr: "Op een bao bun met krokante uitjes en sriracha mayo" },
    { cat: "hoofd", nr: 39, naam: "Crunchy gamba rings", omschr: "Met knoflookmayo en BBQ-saus" },
    { cat: "hoofd", nr: 40, naam: "Seizoenshoofdgerechtje", omschr: "Vraag onze collega's naar het gerechtje van dit seizoen" },
    { cat: "hoofd", nr: 41, naam: "Pastrami New York Style", omschr: "Op een gegrild brioche broodje met cheddarsaus" },
    { cat: "hoofd", nr: 42, naam: "Gepocheerd eitje", omschr: "Met knoflook orzo en Hollandaisesaus", veg: true },
    { cat: "hoofd", nr: 43, naam: "Butter chicken", omschr: "In streetfood style met een naanbroodje en bosui" },
    { cat: "hoofd", nr: 44, naam: "Gyoza", omschr: "Met witte koolsalade, hoisinsaus en krokante uitjes", veg: true },
    { cat: "hoofd", nr: 45, naam: "Kleintje classic USA", omschr: "Burgertje, cheddar, uienchutney en BBQ-saus", z: true },
    { cat: "hoofd", nr: 46, naam: "Gegrilde zalm", omschr: "Met puree van doperwten en antiboise" },
    { cat: "hoofd", nr: 47, naam: "Loaded nacho's", omschr: "Met cheddar en BBQ-saus", veg: true },
    { cat: "hoofd", nr: 48, naam: "Sticky pork belly", omschr: "Buikspek met kimchi, rode peper en Thai-dressing" },

    { cat: "bij", id: "b1", naam: "Truffelfrietje", veg: true },
    { cat: "bij", id: "b2", naam: "Frietje pindasaus", veg: true },
    { cat: "bij", id: "b3", naam: "Klassiek frietje mayo", veg: true },
    { cat: "bij", id: "b4", naam: "Frisse salade", veg: true },
    { cat: "bij", id: "b5", naam: "Broodjes", omschr: "Versgebakken" },

    { cat: "na", nr: 49, naam: "Bastogneparfait", omschr: "Met een druppie karamelsaus", z: true },
    { cat: "na", nr: 50, naam: "Citroensorbetje", omschr: "Verrassend fris!" },
    { cat: "na", nr: 51, naam: "Torentje van yoghurtijs", omschr: "Met ananas, kletskop en citroenschuim" },
    { cat: "na", nr: 52, naam: "Crème brûlée", omschr: "Met een krokant suikerlaagje", z: true },
    { cat: "na", nr: 53, naam: "Pornstar Martini dessert", omschr: "Met passievruchtijs" },
    { cat: "na", nr: 54, naam: "Seizoensnagerechtje", omschr: "Vraag onze collega's naar het gerechtje van dit seizoen" },
    { cat: "na", nr: 55, naam: "Chocoblondie", omschr: "Met pindamousse, zoute karamelparels en toffee-karamelsaus" },
    { cat: "na", nr: 56, naam: "Mislukte appelcake!?!", omschr: "Eigenzinnig lekker", z: true },
    { cat: "na", nr: 57, naam: "Sjoom", omschr: "Jus d'orange met ijs en schuim van mandarijn" },
    { cat: "na", nr: 58, naam: "Marsmousse deluxe", omschr: "Met chocolade sorbetje en karamel" },

    { cat: "kids", id: "k1", naam: "Tomatensoepje" },
    { cat: "kids", id: "k2", naam: "Frikandelletjes" },
    { cat: "kids", id: "k3", naam: "Mini loempia's" },
    { cat: "kids", id: "k4", naam: "Crunchy kipnugget" },
    { cat: "kids", id: "k5", naam: "Mini-pizza" },
    { cat: "kids", id: "k6", naam: "Mini kroketje van rund" },
    { cat: "kids", id: "k7", naam: "Poffertjes pret" },
    { cat: "kids", id: "k8", naam: "Schnitzeltje" },
    { cat: "kids", id: "k9", naam: "Broodje knakworst" },
    { cat: "kids", id: "k10", naam: "Frietje" },
    { cat: "kids", id: "k11", naam: "Cheeseburgertje" },
    { cat: "kids", id: "k12", naam: "Gegrilde zalm" },
    { cat: "kids", id: "k13", naam: "Appelmoes" },
    { cat: "kids", id: "k14", naam: "IJsje van peer" },
    { cat: "kids", id: "k15", naam: "Knetterijsje" },
    { cat: "kids", id: "k16", naam: "2 bolletjes ijs" },
  ],

  dranken: [
    { groep: "Cocktails & Spritzen", items: [
      ["Zusje Gin Tonic", 9.50], ["Mojito", 9.00], ["Espresso Martini", 10.00], ["Pornstar Martini", 10.00],
      ["Limoncello Spritz", 8.50], ["Zusje Spritz", 8.50], ["Aperol Spritz", 8.50],
    ]},
    { groep: "Alcoholvrije cocktails", items: [
      ["Pornstar Martini 0%", 9.40], ["Verse ijsthee Icy Pear", 5.00], ["Mojito 0%", 5.80],
    ]},
    { groep: "Bier van de tap", items: [
      ["Grolsch Premium", 4.20], ["Grolsch Weizen", 5.20], ["Grimbergen Blond", 5.40],
    ]},
    { groep: "Speciaalbieren", items: [
      ["Grimbergen Tripel", 5.90], ["Duvel", 5.90], ["Liefmans Peach", 5.20], ["Chouffe Cherry", 5.90],
    ]},
    { groep: "Alcoholvrije bieren", items: [
      ["Grolsch 0.0", 4.20], ["Grolsch Radler 0.0", 4.00], ["Liefmans Fruitesse 0.0", 5.20], ["Chouffe 0.0", 5.40],
    ]},
    { groep: "Mousserende wijn", items: [
      ["Zusje Cava · glas", 6.90], ["Zusje Cava · fles", 37.00], ["Zusje Cava rosé · glas", 6.90],
      ["Zusje Bubbel 0% · glas", 6.20],
    ]},
    { groep: "Witte wijn", items: [
      ["Zusje Chardonnay · glas", 5.50], ["Zusje zoete witte wijn · glas", 5.50], ["Farina Pinot Grigio · glas", 6.30],
      ["Ramón Bilbao Verdejo · glas", 6.40], ["Twin Island Sauvignon Blanc · glas", 6.50],
      ["Kendall-Jackson Chardonnay · glas", 7.80], ["Chanson Chablis · fles", 45.00],
    ]},
    { groep: "Rosé & rode wijn", items: [
      ["Zusje rosé · glas", 5.50], ["Bisous · glas", 6.10], ["La Vie en Rose · glas", 7.50],
      ["Zusje Merlot · glas", 5.50], ["Al Mercado Syrah · glas", 6.20], ["Salentein Malbec · glas", 6.40],
      ["De Stefani Zusje Esclusivo · glas", 6.90],
    ]},
    { groep: "Frisdranken", items: [
      ["Coca-Cola", 3.70], ["Coca-Cola Zero", 3.70], ["Fanta Orange", 3.70], ["Sprite", 3.70],
      ["Fuze Tea", 3.70], ["Verse ijsthee", 5.00], ["Minute Maid", 3.70], ["Water bruis/plat 0,75L", 4.90],
    ]},
    { groep: "Warme dranken", items: [
      ["Koffie of espresso", 3.70], ["Cappuccino", 4.20], ["Latte macchiato", 4.60], ["Thee", 3.70],
      ["Verse muntthee", 4.60], ["Verse gemberthee", 4.60], ["Chai latte", 5.20],
    ]},
    { groep: "Borrel", items: [
      ["Borrelplank klein", 19.00], ["Borrelplank groot", 29.00],
    ]},
  ],
};
